services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - '4017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongo-data:/data/db

    furia-api:
        image: luanbian/furia-api
        ports:
            - '3001:3001'
        env_file:
            - .env
volumes:
    mongo-data:
